spring:
  application:
    name: sensor-api-hexagonal-study
  datasource:
    url: ${DB_URL:}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      group-id: sensor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID:}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}

app:
  kafka:
    topics:
      sensor-data: ${SENSOR_DATA_TOPIC}

server:
  port: 8081
